# Generated by Django 3.0.6 on 2020-05-28 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_data',
            field=models.DateField(default=datetime.datetime(2020, 5, 28, 18, 38, 50, 394043, tzinfo=utc)),
        ),
    ]
