# Generated by Django 3.0.6 on 2020-05-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_auto_20200529_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationfm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Img1', models.ImageField(upload_to='images/')),
                ('Img2', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Registrationf',
        ),
    ]
